apiVersion: v1
kind: Service
metadata:
  labels:
    app: tms
  name: tms
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: tms
  type: ClusterIP
status:
  loadBalancer: {}
